name: moar

on:
  schedule:
    - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  moar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: g3rv4/GetMoarFediverse@main
        with:
          config_file: ${{ github.workspace }}/data/moar.json
          api_key: ${{ secrets.FAKERELAY_APIKEY }}
